name: PR Preview Cleanup

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    uses: Archetipo95/storybook-github-swiss-knife/.github/workflows/pr-preview-cleanup.yml@114eb93e045bf201cf32ff1da28e900517a53730
    permissions:
      contents: write
      deployments: write
      pages: write
