name: PR Preview Janitor

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  janitor:
    uses: Archetipo95/storybook-github-swiss-knife/.github/workflows/pr-preview-janitor.yml@699c54b46da52c25cc2ff52a883a5a8c769d8625
    permissions:
      contents: write
      deployments: write
      pages: write
      pull-requests: read
