name: PR Preview Publish

on:
  workflow_run:
    workflows: ['PR Preview Build']
    types: [completed]

permissions:
  contents: read

jobs:
  publish:
    uses: Archetipo95/storybook-github-swiss-knife/.github/workflows/pr-preview-publish.yml@7bf16b2a3afb2ed6053d6be5b0822940bde5d6fe
    permissions:
      actions: read
      contents: write
      deployments: write
      pages: write
      pull-requests: write
    secrets:
      passcode_hash: ${{ secrets.STORYBOOK_PREVIEW_PASSCODE_HASH }}
