name: PR Preview Cleanup

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    uses: Archetipo95/storybook-github-swiss-knife/.github/workflows/pr-preview-cleanup.yml@cf7b3413838b0624fe1db6130192417118b47e15
    permissions:
      contents: write
      deployments: write
      pages: write
