name: PR Preview Publish

on:
  workflow_run:
    workflows: ['PR Preview Build']
    types: [completed]

permissions:
  contents: read

jobs:
  publish:
    uses: Archetipo95/storybook-github-swiss-knife/.github/workflows/pr-preview-publish.yml@1cbc94b2dce68abb0f980415cf96228490237a6c
    permissions:
      actions: read
      contents: write
      deployments: write
      pages: write
      pull-requests: write
    secrets:
      passcode_hash: ${{ secrets.STORYBOOK_PREVIEW_PASSCODE_HASH }}
