name: PR Preview Janitor

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  janitor:
    uses: Archetipo95/storybook-github-swiss-knife/.github/workflows/pr-preview-janitor.yml@1cbc94b2dce68abb0f980415cf96228490237a6c
    permissions:
      contents: write
      deployments: write
      pages: write
      pull-requests: read
