name: PR Preview Janitor

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  janitor:
    uses: Archetipo95/storybook-github-swiss-knife/.github/workflows/pr-preview-janitor.yml@0699ab9fa18ab6de13c926afb7cbc210a0a2a0a5
    permissions:
      contents: write
      deployments: write
      pages: write
      pull-requests: read
