name: PR Preview Cleanup

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: read

jobs:
  cleanup:
    uses: Archetipo95/storybook-github-swiss-knife/.github/workflows/pr-preview-cleanup.yml@fdc8ee826fb1ace0150b097a2419cf7ed714c1df
    permissions:
      contents: write
      deployments: write
      pages: write
